### ISSUE TITLE
Permission denied on Record operations for namespaced auth.

### ISSUE THREAD

**Issue by wlynch** [tektoncd/results#142]
# Expected Behavior

Namespaced scoped SA should be able to auth records.

# Actual Behavior

Permission denied. :(

Things work if the user is granted cluster-wide access - this smells like we're not parsing out the namespace correctly so we're making the wrong request.

# Steps to Reproduce the Problem

1. ```yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: result-ro
    subjects:
      - kind: ServiceAccount
        name: default
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: tekton-results-readonly
    ```
2. ```sh
    $ grpc_cli call --channel_creds_type=ssl --ssl_target=tekton-results-api-service.tekton-pipelines.svc.cluster.local --call_creds=access_token=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='result-reader')].data.token}"|base64 --decode) localhost:50051 tekton.results.v1alpha2.Results.ListRecords 'parent: "default/results/4ca70fb5-9cfd-4c0b-bdad-c683c02c7b59"'
    Rpc failed with status code 16, error message: permission denied
    ```

# Additional Info

```yaml
$ k get clusterrole tekton-results-readonly -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-results-readonly
rules:
- apiGroups:
  - results.tekton.dev
  resources:
  - results
  - records
  verbs:
  - get
  - list
```

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Results version:

  23aa0be
