### ISSUE TITLE
Watcher failed to update Record when metadata.generation is not changed

### ISSUE THREAD

**Issue by TianxiangShen** [tektoncd/results#152]
# Expected Behavior
```
  status:
    completionTime: "2022-01-27T07:07:48Z"
    conditions:
    - lastTransitionTime: "2022-01-27T07:07:48Z"
      message: All Steps have completed executing
      reason: Succeeded
      status: "True"
      type: Succeeded
    podName: pipelinerun-with-params3-sum-params-cgrj4-pod-pnbkq
    startTime: "2022-01-27T07:05:37Z"
```

# Actual Behavior
```
records {
  name: "tekton-pipelines/results/3137c0a0-e3e6-40c1-99f1-84e5c68d594d/records/18b63cf4-011d-4a97-bec4-2e528dd5ab74"
  id: "2da6cf12-8466-4752-866e-de07de64e220"
  data {
    type: "tekton.dev/v1beta1.TaskRun"
    value: "{\"kind\": \"TaskRun\", \"spec\": {\"params\": [{\"name\": \"a\", \"value\": \"100\"}, {\"name\": \"b\", \"value\": \"500\"}], \"taskRef\": {\"kind\": \"Task\", \"name\": \"sum-params\"}, \"timeout\": \"1h0m0s\", \"resources\": {}, \"serviceAccountName\": \"default\"}, \"status\": {\"steps\": [{\"name\": \"sum\", \"waiting\": {\"reason\": \"PodInitializing\"}, \"container\": \"step-sum\"}], \"podName\": \"pipelinerun-with-params3-sum-params-cgrj4-pod-pnbkq\", \"taskSpec\": {\"steps\": [{\"name\": \"sum\", \"image\": \"bash:latest\", \"script\": \"#!/usr/bin/env bash\\nsleep 120\\necho -n $(( \\\"$(inputs.params.a)\\\" + \\\"$(inputs.params.b)\\\" ))\\n\", \"resources\": {}}], \"params\": [{\"name\": \"a\", \"type\": \"string\", \"default\": \"1\", \"description\": \"The first integer\"}, {\"name\": \"b\", \"type\": \"string\", \"default\": \"1\", \"description\": \"The second integer\"}]}, \"startTime\": \"2022-01-27T07:05:37Z\", \"conditions\": [{\"type\": \"Succeeded\", \"reason\": \"Pending\", \"status\": \"Unknown\", \"message\": \"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [place-tools place-scripts]\\\"\", \"lastTransitionTime\": \"2022-01-27T07:05:38Z\"}]}
...
```
# Steps to Reproduce the Problem

1. Deploy the Tekton Results on kind cluster
2. Create a PipelineRun

# Additional Info

- Kubernetes version: v1.21.1

- Tekton Pipeline version: v0.26.0

I noticed in pkg/watcher/results/results.go:167, reconciler only updates Record when Record's generation is not equal to object's generation, since the change of pipelineRun/taskRun status won't change generation number, watch can not update the Record even when the status is changed.
