### ISSUE TITLE
Allow users to pass values to the Result.Annotations and RecordSummary.Annotations fields

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/results#343]
### Feature request

The Result and RecordSummary types have an Annotations field described as:

>Key-value pairs representing arbitrary underlying record data that clients want to include that aren't covered by the above fields.

However, currently, the system doesn't provide any hook that allows users to pass values to these fields.

#### Proposal

Create two new annotations with a special meaning:

* results.tekton.dev/resultAnnotations
* results.tekton.dev/recordSummaryAnnotations

Integrators should set those annotations in their PipelineRuns and/or TaskRuns to pass arbitrary key/values to the respective Annotations fields. During the reconciliation loop, the Watcher will look for those annotations and populate the Result and/or RecordSummary accordingly. For instance:

```yaml
# Hypothetical PipelineRun
annotations:
  results.tekton.dev/resultAnnotations: '{"pull": "42", "repo": "tektoncd/results", "author": "alan-ghelardi"}'
  results.tekton.dev/recordSummary: '{"commit": "abcd1234", "branch": "main"}'
```
 

### Use case

Users may take advantage of those annotations to pass arbitrary key/value pairs to the Result object. When this [feature](https://github.com/tektoncd/results/issues/259) is finally out, users will be able to query results efficiently by using plain SQL queries behind the scenes. Since the records table tends to host very large blobs due to the size of PipelineRuns, querying results is much more efficient. With this feature in place, users may annotate results with relevant metadata (e.g. pull request number, commit ID, branch, author, etc.) and later on, implement sophisticated searches based upon those values to find the corresponding runs.
