### ISSUE TITLE
Passing Storage(S3, AWS) keys via kubernetes secrets

### ISSUE THREAD

**Issue by khrm** [tektoncd/results#469]
### Feature request

At present, we are passing S3 secrets as config. We need to use secrets to pass these configurations.

**Comment by jkandasa** [comment]
It is possible to inject custom secret values as env into `tekton-results-api` deployment as follows,
I think no additional changes required in results code base.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-api
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    # omitted ...
    spec:
      containers:
        - env:
            # omitted ...
          image: gcr.io/tekton-releases/github.com/tektoncd/results/cmd/api:v0.6.0@sha256:e3760a8fb8e8c056e247595d560dfc9aab38cee4a9c512fe5c198c7b88a923bd
          name: api
          envFrom: # supply your custom secret keys as env variable
            - secretRef:
                name: my_custom_s3_secret
                optional: true
```

I have created a PR in operator to support custom secret: https://github.com/tektoncd/operator/pull/1547
