### ISSUE TITLE
Liveness and Readiness probes fail with recommended certificate setup

### ISSUE THREAD

**Issue by kbristow** [tektoncd/results#521]
# Expected Behavior
Expected that `tekton-results-api` pod would become healthy.

# Actual Behavior
The `tekton-results-api` pod does not become healthy. Readiness and Liveness probes fail with 503 response. Doing a port-forward on the `tekton-results-api`'s  `api` container and doing a curl to the `/healthz` endpoint returns the following error:

```
{"code":14,"message":"connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for tekton-results-api-service.tekton-pipelines.svc.cluster.local, not localhost\"","details":[]}
```

I am using self-signed certificates managed by certman. Adding `localhost` to the `dnsNames` list results in the Liveness and Readiness probes passing. As per [prerequisites](https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/docs/install.md?plain=1#L27) this is not the recommended config.

# Steps to Reproduce the Problem

1. Install Certman
2. Install Tekton Pipelines (v0.38.4)
3. Create Certificate and Certificate issuer as below:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tekton-results-selfsigned-issuer
  namespace: tekton-pipelines
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tekton-results-tls-cert
  namespace: tekton-pipelines
spec:
  dnsNames:
  - tekton-results-api-service.tekton-pipelines.svc.cluster.local
  # - localhost # uncomment this to make probes pass
  issuerRef:
    kind: Issuer
    name: tekton-results-selfsigned-issuer
  secretName: tekton-results-tls
```
4. Install Tekton Results following all install instructions besides certificate generation (v0.7.0)
5. Observe unhealthy `tekton-results-api` pod

# Additional Info

- Kubernetes version:

```
Server Version: v1.23.17-eks-c12679a
```

- Tekton Pipeline version:

```
v0.38.4
```

**Comment by xinnjie** [comment]
Readiness/Liveness probe don't check certificate verification . 
You should curl with `--insecure` option, and see what happened.
Normally it should be like this:
```
> curl --insecure  https://localhost:8080/healthz
{"status":"SERVING"}
```

If not, I suspect something else went wrong, like some configuration problem.

**Comment by kbristow** [comment]
I have indeed used the insecure option for curl. It looks like the actual go http server is returning the body i showed because the certificate loaded does not have localhost as a dns name. In the example above are you using a cert generated using the instructions [here](https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/docs/install.md?plain=1#L27) or are you also including localhost in the subject alternate names?

**Comment by xinnjie** [comment]
> In the example above are you using a cert generated using the instructions [here](https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/docs/install.md?plain=1#L27) or are you also including localhost in the subject alternate names?

I followed the instructions, which not include  localhost in the subject alternate names.

> It looks like the actual go http server

Yes, I think so after carefully reading the error message.

Have no idea right now. Maybe you could turn on debug logging to see what is happening in Results API Server .

**Comment by xinnjie** [comment]
1. Change logging level to debug. 
` kubectl -n tekton-pipelines edit cm tekton-results-config-logging `
set as below
```
zap-logger-config: |
    {
      "level": "debug",
      "development": true,
     .....
    }

```
2.  curl again
3.  check Results API Server logs

**Comment by kbristow** [comment]
So interestingly, if i port forward to the service as you have done, I do not get the error. If I port forward to the pod, i do.

So example of what I was doing which returns a **503** code and the error response I showed earlier:
```
kubectl port-forward -n tekton-pipelines pods/tekton-results-api-57845986d9-8lrfw 8080:8080
```

Regardless, I bumped the logging level, and I tried again. The curls do not actually correlate to anything in the logs. There are a bunch of tls errors which seem to match the cadence of the probes:

```
2023/07/12 13:10:45 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"warn","ts":1689167445.1729739,"caller":"api/main.go:116","msg":"Kubernetes RBAC authorization check disabled - all requests will be allowed by the API server"}
{"level":"info","ts":1689167445.3304975,"caller":"api/main.go:195","msg":"Prometheus server listening on: 9090"}
{"level":"info","ts":1689167445.3309426,"caller":"api/main.go:237","msg":"gRPC and REST server listening on: 8080"}
2023/07/12 13:10:54 http: TLS handshake error from 127.0.0.1:34026: remote error: tls: bad certificate
2023/07/12 13:11:04 http: TLS handshake error from 127.0.0.1:33524: remote error: tls: bad certificate
2023/07/12 13:11:09 http: TLS handshake error from 127.0.0.1:33542: remote error: tls: bad certificate
2023/07/12 13:11:14 http: TLS handshake error from 127.0.0.1:44222: remote error: tls: bad certificate
2023/07/12 13:11:24 http: TLS handshake error from 127.0.0.1:33502: remote error: tls: bad certificate
```

Here the events shown from a describe on the pod:
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m20s                  default-scheduler  Successfully assigned tekton-pipelines/tekton-results-api-57845986d9-8lrfw to ip-10-123-123-12.af-south-1.compute.internal
  Normal   Pulled     4m40s (x2 over 6m19s)  kubelet            Container image "gcr.io/tekton-releases/github.com/tektoncd/results/cmd/api:v0.7.0@sha256:08aea538dc699c27715523fc89115cc805a0b5838c924868907189fcc99099b9" already present on machine
  Normal   Created    4m40s (x2 over 6m19s)  kubelet            Created container api
  Normal   Killing    4m40s                  kubelet            Container api failed startup probe, will be restarted
  Normal   Started    4m39s (x2 over 6m19s)  kubelet            Started container api
  Warning  Unhealthy  70s (x31 over 6m10s)   kubelet            Startup probe failed: HTTP probe failed with statuscode: 503
```

Note the 503 - which assumed meant the result was the same as that from the curl I was doing.

**Comment by xinnjie** [comment]
I dig a little.

## Background:
Results API Server took a little trick to server as  GRPC server and RESTful server: on port 8080, it register both grpc service and http service and process request base on http protocol version and `Content-Type`.
So one health check flow like this: (1)Kubelet probe -> (2)Results Server RESTful service -> (3)Results Server GRPC service.

## Why Results API Server complained `tls: bad certificate`?
Problem  occur when (2)->(3) happened. Results Server need to dial itself and forward this health check request with  in GRPC format. Because original http request do not have authority header and the path  Kubelet request is simply `http://localhost:8080`,  so TLS handshake failed.

## Workaround 
Add environment variable `TLS_HOSTNAME_OVERRIDE` as `tekton-results-api-service.tekton-pipelines.svc.cluster.local` to Results API Server pod configuration.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tekton-pipelines
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: ....
          env:
            - name: TLS_HOSTNAME_OVERRIDE
              value: tekton-results-api-service.tekton-pipelines.svc.cluster.local
```

@sayan-biswas  Is here something wrong here? 
As document says:
> TLS_HOSTNAME_OVERRIDE   Override the hostname used to serve TLS. This should not be set (or set to the empty string) in production environments.  

But it seems even in production environment, `TLS_HOSTNAME_OVERRIDE` need to be set to make liveness probe working.
