### ISSUE TITLE
Postgres STS fails to start - mkdir: cannot create directory ‘/bitnami/postgresql/data’

### ISSUE THREAD

**Issue by kbristow** [tektoncd/results#522]
# Expected Behavior
Postgres created as part of the release manifests would start up successfully.

# Actual Behavior
The postgres pod does not become healthy. The pod fails and enters crashloopbackoff with the following error in the logs:

```
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

This appears similar to this issue: https://github.com/bitnami/charts/issues/1210

Investigating the recommendation [here](https://github.com/bitnami/charts/issues/1210#issuecomment-1179827873) i added an init container that looks as follows which resolves the issue:

```
initContainers:
  - name: init-chmod-data
    image: docker.io/bitnami/bitnami-shell:11-debian-11-r130
    imagePullPolicy: "IfNotPresent"
    resources:
      limits: {}
      requests: {}
    command:
      - /bin/sh
      - -ec
      - |
        chown 1001:1001 /bitnami/postgresql
        mkdir -p /bitnami/postgresql/data
        chmod 700 /bitnami/postgresql/data
        find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name "conf" -not -name ".snapshot" -not -name "lost+found" | \
          xargs -r chown -R 1001:1001
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: postgredb
        mountPath: /bitnami/postgresql
```

I took the above from the output of running the below (with slight modifications):
```
helm template my-release oci://registry-1.docker.io/bitnamicharts/postgresql --set volumePermissions.enabled=true
```

Note that I am using EKS with ebs volumes and a storage class as below if useful:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

# Steps to Reproduce the Problem

1. Install Tekton Results (v0.7.0) on eks 1.23 with ebs volume
2. Observe error with postgres pod

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
v1.27.3
```

- Tekton Pipeline version:

```
v0.38.4
```
