### ISSUE TITLE
tkn-results CLI flags are broken, unknown flag error

### ISSUE THREAD

**Issue by avinal** [tektoncd/results#567]
# Expected Behavior

`tkn-results` should not show errors for existing flags
# Actual Behavior
`tkn-results` shows unknown flag error

![image](https://github.com/tektoncd/results/assets/74113200/20b5c7fb-92a6-4fda-bb1c-a490ca3c420b)

# Steps to Reproduce the Problem

1. Checkout the latest main branch 3e249c3315b2eba9c14523372ff7a4d6ea6a2cdd
2. Build `tkn-results`
3. Configure `tkn-results` config
4. Run a command with flags `tkn-results list default --filter="summary.type=TASK_RUN"`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```yaml
    clientVersion:
      buildDate: "2023-07-19T12:20:54Z"
      compiler: gc
      gitCommit: fa3d7990104d7c1f16943a67f11b154b71f6a132
      gitTreeState: clean
      gitVersion: v1.27.4
      goVersion: go1.20.6
      major: "1"
      minor: "27"
      platform: linux/amd64
    kustomizeVersion: v5.0.1
    serverVersion:
      buildDate: "2022-10-25T19:35:11Z"
      compiler: gc
      gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
      gitTreeState: clean
      gitVersion: v1.25.3
      goVersion: go1.19.2
      major: "1"
      minor: "25"
      platform: linux/amd64
  ```

- Tekton Pipeline version: v0.47.2

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

# Additional Info
Likely caused by #461
